### PR TITLE
No match session closed 2

### PR DESCRIPTION
**Pull request by b3njamint**
### Summary 

This pull request is the revamped version of No match, session closed :( #142.
It adds an email template for students who do not have a match after about a 6-week period, which the LSC users would keep track of manually. 

- [ ] implemented X
- [x] fixed Y

### Test Plan 

I tested in the staging app: https://zing-lsc.web.app/

The template shows up!
Screen Shot 2023-03-30 at 4 44 03 PM

The contents are correctly filled in as well.
Screen Shot 2023-03-30 at 4 44 09 PM

### Notes 

Will added the template to prod, so that part is taken care of.

### Breaking Changes 

- Added template, so Firebase is modified.

### CODE REVIEW

**Review by wizhaaa — CHANGES_REQUESTED** [review]
Good work. I think you still have to export the updated emulator Firestore to have the new email template. 

Achievable by running these commands which will update the files in `./emulator` to update the default imported firestore data. 

image

**Comment by Coreball** [comment]
> Good work. I think you still have to export the updated emulator Firestore to have the new email template.
> 
> Achievable by running these commands which will update the files in `./emulator` to update the default imported firestore data.
> 
> image

@wizhaaa these instructions result in the emulator being exported to backend/functions/src/utils/emulator, not the backend/functions/emulator that the `npm run emulate` command pulls from when running the backend from backend/functions

**Comment by wizhaaa** [comment]
@Coreball You are so correct. I will update the notion doc to make sure to `cd` back the `./functions`. 

So @b3njamint, I think you should probably just revert the last commit and make sure to change the directory back to `./functions` and make sure the export updates the files in the `functions/emulator` folder.

**Comment by b3njamint** [comment]
> @Coreball You are so correct. I will update the notion doc to make sure to `cd` back the `./functions`.
> 
> So @b3njamint, I think you should probably just revert the last commit and make sure to change the directory back to `./functions` and make sure the export updates the files in the `functions/emulator` folder.

I spoke with Miranda and just replaced the emulator folder with the new emulator folder generated by the above instructions.

**Review by mluo24 — APPROVED** [review]
lgtm now! Thanks Benji for working on this. Just resolve merge conflicts (for the emulator, accept all your own) and you should be good to go.

**Review by wizhaaa — APPROVED** [review]

**Comment by mluo24** [comment]
you have more merge conflicts from the emulator. I think Will accidentally merged in populated emulator data. Make sure to consolidate your conflicts with his emulator changes, and then remove all of the courses and students and then push.

**Pull request closed without merging**
