### PR TITLE
Firebase Emulator Utils Updated for Semester Settings

### PR DESCRIPTION
**Pull request by wizhaaa**
# Summary 

To the Firebase emulator:
Adds the utils with a semester doc that stores the current semester and a list of all semesters. 

Added to support the settings page implementation. 

image

### CODE REVIEW

**Comment by JustKong13** [comment]
Nice will! when this gets merged in we will now be able to have a dropdown menu in the settings page that has semester options to choose from. Further testing might be needed to make sure the frontend and backend integration is done well, but a very helpful and necessary change to the deployment database. 

There's also a couple of small merge conflicts which need to be resolved.

**Review by JustKong13 — CHANGES_REQUESTED** [review]
Nice will! when this gets merged in we will now be able to have a dropdown menu in the settings page that has semester options to choose from. Further testing might be needed to make sure the frontend and backend integration is done well, but a very helpful and necessary change to the deployment database. 

There's also a couple of small merge conflicts which need to be resolved.

**Comment by wizhaaa** [comment]
> Nice will! when this gets merged in we will now be able to have a dropdown menu in the settings page that has semester options to choose from. Further testing might be needed to make sure the frontend and backend integration is done well, but a very helpful and necessary change to the deployment database. 
> 
> 
> 
> There's also a couple of small merge conflicts which need to be resolved. 

@JustKong13 ME FIX GOOD NOW

**Review by JustKong13 — APPROVED** [review]
Lgtm! conflicts are resolved and my prior comments still stand :D

**Pull request merged**
