### PR TITLE
Updated README with Fall 2022 members 

### PR DESCRIPTION
**Pull request by rgu0114**
### Summary 
Added names and roles to README

### CODE REVIEW

**Comment by Coreball** [comment]
Could you also add the Summer 2022 people and put the Fall 2022 list in alphabetical order within each role like previous semesters? (Also where's @JustKong13 ?)

**Comment by rgu0114** [comment]
> Could you also add the Summer 2022 people and put the Fall 2022 list in alphabetical order within each role like previous semesters? (Also where's @JustKong13 ?)

Oh I thought Justin might want to do another PR with his name for dev portfolio 1, I can add him tho

**Comment by rgu0114** [comment]
Was Summer 2022 same as Fall 2022 + Will?

**Comment by Coreball** [comment]
@rgu0114 the Google Sheet named "Zing Team" in the Google Drive folder should be accurate for Summer 2022, though Sean & Alyssa stopped coming to meetings for a good chunk of the summer

**Comment by Coreball** [comment]
Oh I just realized that some of the Spring 2022 people like designers weren't added to this README, could you add them as well?

**Review by b3njamint — APPROVED** [review]
Edit: Sorry, didn't see Changyuan's comment.

**Review by Coreball — APPROVED** [review]

**Pull request merged**
